theme: jekyll-theme-minimal
# theme: jekyll-text-theme

title: Santiago Gonz√°lez Silot Portfolio - NLP Data Scientist
description: Brief portfolio with some of my Data Science projects that I developed during my career.
